extends:
  - "airbnb"
  - "prettier"
  - "prettier/react"
parser: "babel-eslint"
env:
  es6: true
  browser: true
  node: true
plugins:
  - "react"
  - "prettier"
parserOptions:
    ecmaVersion: 2016
    sourceType: "module"
    ecmaFeatures:
      jsx: true
rules:
  "prettier/prettier": "error"
